- src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
- src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
- src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeRequest.java
- src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeResponse.java
- src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeVO.java
- src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeService.java
- src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
- Recipe-Likes API 
- 유저의 좋아요 여부 & 클릭시 API 입니다.
- 기본 유저는 Default User를 생성해 사용하였고 추후 security 파트완료시 코드 수정하겠습니다.
- API 목록
- (GET) /recipe-likes/{recipeId} : 해당 레시피에 좋아요 여부
- (POST) /recipe-likes/{recipeId} : 해당 레시피에 좋아요 누를 때  수정
- 레시피 좋아요 여부
- like 클릭 시 API
- 현재 /recipe-likes/{recipeId}로 구현했는데 PathVariable이 괜찮을지 param으로 좋을지 추후 프론트 담당자 분과 의견 나누려고 합니다! 의견있으시면 말씀해주세요!
- Close  #34
> Feat : 레시피 좋아요 API

- src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
- src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- src/main/java/com/example/dgbackend/global/validation/annotation/CheckPage.java
- src/main/java/com/example/dgbackend/global/validation/annotation/ExistCombination.java
- src/main/java/com/example/dgbackend/global/validation/validator/CombinationExistValidator.java
- src/main/java/com/example/dgbackend/global/validation/validator/PageCheckValidator.java
- 특정 오늘의 조합에 작성된 댓글을 페이징하여 조회하는 API입니다.
- 오늘의 조합에 작성된 댓글을 조회할 때 부모 댓글과 자식 댓글을 반환합니다.
1. 실행 결과
2. Page Validator 실행 결과 (현재는 page 번호 시작을 0으로 설정해두었습니다.)
3. Combination Validator 실행결과
- close #57
> [FEAT] 오늘의 조합 댓글 조회 API 개발

- src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
- src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryService.java
- src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/member/Member.java
- 오늘의 조합 상세 조회 시 CombinationImage 정보 같이 전달하기
- 특정 오늘의 조합에 좋아요 상태 여부 전달하기
- 오늘의 조합 상세 조회 시 보여지는 Image 데이터 추가 전달하기
- 로그인 사용자가 특정 오늘의 조합에 좋아요 눌렀는지 확인하는 데이터 추가 전달하기
-
- close #47
> FIX : 오늘의 조합 상세 조회에 CombinationImage, CombinationLike 정보 추가 전달

- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentRequest.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/member/Member.java
- 오늘의 조합 댓글 수정 API 개발
- 특정 오늘의 조합에 작성된 댓글을 수정하는 API를 구현합니다.
1. 수정 API 실행결과
2. DB 변경 사항 확인
- close #60
> Feat: 오늘의 조합 댓글 수정 API 개발

- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
- src/main/java/com/example/dgbackend/domain/member/Member.java
- src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
주류 추천 삭제 API
Path variable로 recommend id를 입력받아 해당 추천을 삭제하는 API.
S3의 이미지와 DB에서 recommend 객체를 삭제한다.
- 추천 생성단계에서 imageUrl을 "temp"로 저장하고 있던 내용을 수정함
- close #63
> Feat: 추천 삭제 API

- src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- Controller, Service, Repository 구현
- 좋아요 10개 이상 게시글 조회
- 주간 베스트 조합 조회 API를 구현합니다.
- 카일로의 오늘의 조합 조회 API를 참고하여 진행하였습니다.
```java
Page<Combination> findCombinationsByLikeCountGreaterThanEqualAndStateIsTrueOrderByCreatedAtDesc(
Long likeCount, PageRequest pageRequest);
```
- 해당 메소드를 이용해 넘겨 받은 좋아요 수 이상, 상태가 True 인 게시글들을 받습니다.
- 좋아요 수가 우선이라고 생각하고 진행하였습니다. 또한 좋아요 수는 임시로 10개 이상으로 해놓았는데, 기획에 맞춰 추후 수정하도록 하겠습니다.
- 아래와 같이 게시글 좋아요 수가 10개 이상인 오늘의 조합 글만 조회하도록 하였습니다.
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"combinationList": [
{
"title": "테스트",
"combinationImageUrl": null,
"likeCount": 30,
"commentCount": 0,
"hashTageList": []
}
],
"listSize": 1,
"totalPage": 1,
"totalElements": 1,
"isFirst": true,
"isLast": true
}
}
```
- 코딩 컨벤션을 적용하느라 수정된 파일들이 많아지게 됐습니다. 양해 …
> Feat: 주간 베스트 조합 조회 API

- src/main/java/com/example/dgbackend/domain/combination/Combination.java
- src/main/java/com/example/dgbackend/domain/combinationlike/CombinationLike.java
- src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
- src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
- src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryService.java
- src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
- 오늘의 조합 좋아요 누르기 API를 구현합니다.
- 메이슨과 제가 구현했던 방식을 섞어서 구현해보았는데, 메이슨과 달리 좋아요 여부 API는 구현하지 않았습니다. 프론트와 상의하에 필요하다고 하면 추후 구현하도록 하겠습니다.
- 기본 유저는 Long memberId를 통해 구현했는데, 이 또한 로그인이 완료되면 추후 수정하도록 하겠습니다.
- 한번 누를 시 
- 다시 한번 누를 시
- 이슈 번호를 착각해 카일로의 #75 번 PR에 커밋이 따라갔습니다,,, revert 후 push 하였는데, 이게 올바른 방법인진 모르겠습니다 ㅠㅠ 다행히 해당 PR에 제가 수정한 커밋은 반영되지 않은 것 같습니다.. 앞으로는 주의하도록 하겠습니다!
- close #76
> Feat: 오늘의 조합 좋아요 누르기 API

- src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
- src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
- src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipelike/RecipeLike.java
- src/main/java/com/example/dgbackend/domain/recipelike/service/RecipeLikeServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- 레시피 Count 변경 기능 추가
- 레시피 댓글, 좋아요 변경 시 해당 레시피의 Count 변경될 수 있게 하였습니다
- 수정사항
- 레시피 댓글 삭제시
- 레시피 댓글 등록시
- 레시피 댓글 처음 좋아요일 때
- 레시피 좋아요 바뀔 때
---
- Close  #95
> Feat : 레시피 Count 변경 기능 추가

- src/main/java/com/example/dgbackend/domain/combination/Combination.java
- src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
- src/main/java/com/example/dgbackend/domain/combination/dto/CombinationRequest.java
- src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandService.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionQueryService.java
- src/main/java/com/example/dgbackend/domain/hashtagoption/service/HashTagOptionQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- src/main/java/com/example/dgbackend/global/config/SwaggerConfig.java
- src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
- src/main/java/com/example/dgbackend/global/jwt/config/WebConfig.java
- src/main/java/com/example/dgbackend/global/jwt/controller/JwtController.java
- src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
- src/main/java/com/example/dgbackend/global/jwt/resolver/MemberArgumentResolver.java
- src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
- src/main/java/com/example/dgbackend/global/validation/annotation/CheckCombinationOwner.java
- src/main/java/com/example/dgbackend/global/validation/interceptor/CheckCombinationOwnerInterceptor.java
- 오늘의 조합 API에서 로그인 사용자 정보가 필요한 부분을 수정하였습니다.
- @MemberObject를 적용하여 로그인 사용자 정보가 필요한 API에 적용하였습니다.
- 기존의 Hard Delete 방식에서 Soft Delete 방식으로 변경하였습니다.
- HandlerInterceptor를 구현하여 작성자가 아닌 사용자의 수정, 수정조회, 삭제 권한을 제한하였습니다.
1. 오늘의 조합 홈 API
2. 오늘의 조합 상세보기 API
3. 오늘의 조합 수정 페이지 조회 API
4. 오늘의 조합 수정 API
5. 오늘의 조합 삭제 API
-
- close #101
> Fix: 오늘의 조합 API 수정 & 로그인 사용자 정보 어노테이션 추가 & Soft Delete 적용

- src/main/java/com/example/dgbackend/domain/recommend/Recommend.java
- src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
- src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandService.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- RecommendController에 MemberObject어노테이션 적용
- Hard Delete -> Soft Delete 변경
- ResponseDTO 동일 기능 객체 통합
- Recoomend 관련 ErrorStatus 수정 (code가 중복되어있었음)
내가 추천 받은 조합 리스트 조회 API 변경 (path variable -> MemberObject annotation)
Recommend 도메인 객체 soft delete 구현
주류 추천 요청 API (헤더의 Authroization부분에 토큰 입력)
나의 주류 추천 리스트 API (헤더의 Authorization부분에 토큰 입력, 삭제시 삭제된 객체 출력되지 않음)
-
- close #102
> Fix: Recommend 도메인 Member어노테이션 추가 및 Soft Delete구현

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/combinationimage/controller/CombinationImageController.java
- src/main/java/com/example/dgbackend/domain/combinationimage/service/CombinationImageCommandServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- src/main/java/com/example/dgbackend/global/util/DateTimeUtils.java
- src/main/java/com/example/dgbackend/global/validation/validator/CombinationExistValidator.java
- 로그인 사용자 정보를 적용하여,  사용자 정보가 필요한 API에 기능을 추가합니다.
- 오늘의 조합 댓글 부분의 API를 최종 검토합니다.
1. 오늘의 조합 댓글 조회 API
2. 오늘의 조합 댓글 작성 API
3. 오늘의 조합 댓글 수정 API
4. 오늘의 조합 댓글 삭제 API
- 105번 이슈에 마지막 2개의 커밋이 잘못 Related 되어 있습니다.
- 실제 적용은 fix/combination 브랜치에 적용되어 있고, fix/combination-comment에는 적용되어 있지 않습니다.
- close #105
> FIX: 오늘의 조합 댓글 관련 API 및 로그인 사용자 정보 적용

- src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
- src/main/java/com/example/dgbackend/global/jwt/controller/JwtController.java
- src/main/java/com/example/dgbackend/global/jwt/handler/CustomLogoutHandler.java
- src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
- 회원가입 및 로그인 처리 후 Refresh Token 전달 방법 수정
- 회원가입 및 로그인 처리 후 Refresh Token을 Header에 담아 전달합니다.
- 로그아웃 시 Cookie가 아닌 Header에 RefreshToken을 삭제
**1. 회원가입 및 로그인 실행결과**
**2. 로그아웃 실행결과**
> Redirect Url을 "/"로 설정했는데 프론트와 상의 후 수정
**3. Access Token 재발급 실행결과**
- close #109
> fix: 소셜 로그인 처리 후 Refresh Toekn 전달 방법 수정

- src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandService.java
- src/main/java/com/example/dgbackend/domain/hashtag/service/HashTagCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
- src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
- src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipe_hashtag/RecipeHashTag.java
- src/main/java/com/example/dgbackend/domain/recipe_hashtag/dto/RecipeHashTagResponse.java
- src/main/java/com/example/dgbackend/domain/recipe_hashtag/repository/RecipeHashTagRepository.java
- src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagService.java
- src/main/java/com/example/dgbackend/domain/recipe_hashtag/service/RecipeHashTagServiceImpl.java
- 프론트 요청에 의해 해시태그 기능 추가하였습니다.
- RecipeHashTag 도메인 추가하였습니다.
- Recipe Entity에 recipeHashTagList Set 형으로 추가하였습니다.
🎏 create
🎏 patch
-
Close #112
> Feature : 레시피북 해시태그 추가

- src/main/java/com/example/dgbackend/domain/combinationlike/repository/CombinationLikeRepository.java
- src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
- 좋아요 로직을 수정합니다.
- `existsByCombinationAndMember`  -> `existsByCombinationAndMemberAndStateIsTrue` 로 수정하였습니다.
- 따라서 State가 True가 아닐 때에는 False로 표기됩니다.
-
-
> Fix: 오늘의 조합 좋아요 여부 로직 수정

- src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
- src/main/java/com/example/dgbackend/global/config/SecurityConfig.java
- 오늘의 조합 API URL {recommendId} 부분 제거
- 댓글 조회 응답값에서 자식 댓글을 카운트 못 하는 오류 해결
- 오늘의 조합 작성 API에서 path variable 삭제
- 댓글 조회 DTO 수정
```java
.listSize(comments.getContent().size())
```
> 댓글 자식도 카운트 되도록 함.
-
- close #140
> Fix: 오늘의 조합 API URL 및 댓글 DTO 수정

- src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
- src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
- 레시피 / 레시피 댓글에 유저 정보 추가
- 레시피 / 레시피 댓글에 유저 정보 추가하였습니다
- 기존 MemberResponse에 만들어진 클래스가 있어 활용하였습니다
-
Close  #149 
-
> Refactor : 레시피 / 레시피 댓글에 유저 정보 추가

- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
- 오늘의 조합 댓글 조회 DTO 수정
- CommentReult에 memberId 정보 추가
> 로그인한 사용자와 댓글 작성자의 정보를 비교하여, 권한 있는 사용자에게만 수정 및 삭제 버튼이 보이도록 하기 위함
-
-
> [FIX]: CommentResult memberId 추가

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- 게시글 검색 시 삭제된 게시글도 검색되는 오류를 수정하였습니다.
- JPA 메서드를 수정하여 State가 True인 게시글들만 조회합니다.
- `findCombinationsByTitleContaining` -> `findCombinationsByTitleContainingAndStateIsTrue` 로 수정
-
-
> Fix: 검색 시 State True 게시글만 조회

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
- 좋아요 삭제 여부가 조회할 때 반영 안 되는 부분 수정.
- 각 Repository에 해당 Like 테이블 state 값 true인 것만 불러오는 부분 추가 
- 포스트맨 호출 
- DB
-
- #156
> refactor: 좋아요 삭제 여부 반영

- src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentRequest.java
- src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
- src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
- src/main/java/com/example/dgbackend/domain/report/dto/ReportRequest.java
- src/main/java/com/example/dgbackend/domain/report/service/ReportServiceImpl.java
Related: #171
- 신고당한 Member Id를 받아와서 회원 정지시킬 수 있도록 수정하고 댓글 생성 시 오류를 해결합니다.
-
-
-
> Fix: 신고당한 Member Id 추가 및 댓글 생성 오류 해결

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- 커뮤니티 검색 시 최신순으로 조회하도록 메서드를 수정합니다.
- JPA 메서드에 `OrderByCreatedAtDesc` 를 추가하였습니다.
-
- close #178
> Fix: 커뮤니티 검색 시 최신순으로 조회

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
- src/main/java/com/example/dgbackend/domain/memberblock/MemberBlock.java
- src/main/java/com/example/dgbackend/domain/memberblock/controller/MemberBlockController.java
- src/main/java/com/example/dgbackend/domain/memberblock/dto/MemberBlockRequest.java
- src/main/java/com/example/dgbackend/domain/memberblock/dto/MemberBlockResponse.java
- src/main/java/com/example/dgbackend/domain/memberblock/repository/MemberBlockRepository.java
- src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockService.java
- src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- 차단 API 관련한 기능을 개발하였습니다.
- 오늘의 조합, 주간 베스트 조합 "조회" 관련 API를 MemberBlock 테이블에 따라 조회 쿼리문을 수정하였습니다.
- 레시피 관련 "조회" API를 MemberBlock 테이블에 따라 조회 쿼리문을 수정하였습니다.
- MemberBlock 테이블에 아무 값도 없는 형태입니다. 이 상상태에서 아래와 같은 요청을 보냅니다.
- 그러면 아래와 같이 MemberBlock 테이블에 데이터가 생기게 됩니다.
```java
@Query("SELECT c FROM Combination c WHERE c.member NOT IN (SELECT mb.blockedMember FROM MemberBlock mb WHERE mb.member.id = :memberId) AND c.state = :state ORDER BY c.createdAt DESC")
Page<Combination> findAllByStateOrderByCreatedAtDesc(Boolean state, PageRequest pageRequest, Long memberId);
```
- 그렇게 생기게 된 DB에 따라 위와 같은 쿼리문을 통해 MemberBlock 테이블에 있는 멤버라면 제외하고 글을 조회하게 됩니다.
- 레시피에서도 동일하게 적용됩니다.
```java
private void isBlocked(Long combinationId, Long memberId) {
Combination blockedCombination = …
```
> Feat: 차단 API 구현

- src/main/java/com/example/dgbackend/domain/member/Member.java
- src/main/java/com/example/dgbackend/global/jwt/controller/JwtController.java
- src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
- Apple소셜로그인 api구현
- 로그인/가입시 헤더의 newMember변수에 true/false로 표시합니다.
-
-
-
> [Feat]auth apple api

- src/main/java/com/example/dgbackend/domain/member/repository/MemberRepository.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
- 회원가입 시 중복 닉네임 거르기
- 닉네임이 동일할 경우 API 예외처리 
-
- #195
> fix: 회원가입 시 중복 닉네임 거르기

- src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
- src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
- 헤더에서 전달하던 newMember변수를 헤더에서 제거하였습니다.
- newMember변수를 responseBody로 전달하도록 수정하였습니다.
- 새로운 유저는 true, 기존 유저는 false를 반환합니다.
- 이미 존재하는 유저
- 새로운 유저
-
- #200
> change: newMember 전달 방식 변경

- src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberService.java
- 프론트엔드 요구사항 반영 
- 멤버 정보 조회 시 Reponse Body에 Provider 값 추가하여 전송
- 오늘의 조합 좋아요 로직 변경
- 기존 멤버를 name으로 찾아오는 쿼리 대신 id로 찾아오는 쿼리로 변경 
-
- #203
> fix: 프론트엔드 요구사항 반영

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
- 좋아요한 게시글 목록에서 차단을 적용합니다.
- 오늘의 조합 좋아요한 게시글 목록 API 차단을 적용했습니다.
- 레시피 좋아요한 게시글 목록 API 차단을 적용했습니다.
-
- close #210
> Fix: 좋아요한 게시글 목록 차단 적용

- src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
- src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
- src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
- src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
- src/main/java/com/example/dgbackend/global/common/MemberValidator.java
- src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
- 레시피 도메인 리팩토링과 오류를 해결하고, 멤버 검증 기능을 구현하였습니다.
- 제가 작업한 파일들에 대해서 코딩 컨벤션을 적용하였습니다. 코딩 컨벤션은 다른 이슈를 통해 모든 파일에 적용할 예정입니다!
- 간단히 요약하면, 레시피 도메인 오류 해결 및 멤버 어노테이션 적용을 위해 코드를 수정하였습니다.
- 해당 부분을 진행하면서, 멤버 검증 클래스를 추가하였습니다. (MemberValidator) 위치: global - common - MemberValidator 클래스
- 해당 클래스는 여러분들도 사용하면 좋을 것 같습니다!
- viewer와 writer가 동일한지 검증하는 로직입니다. Combination 도메인 API에도 적용하도록 하겠습니다.
- `isMatch` 또는 `match`함수를 를 본인 기능에 맞게 사용하시면 됩니다.
- 따라서 레시피 댓글 작성 시 현재 로그인한 멤버에 맞게 Entity 저장하도록 수정하여 에러를 해결하였습니다!
- `ErrorStatus` 에 `_INVALID_MEMBER`를 추가하였으니, 사용하시면 됩니다.
- 오래걸려서 죄송합니다 ㅠㅠ 앞으로 빠르게 작업하도록 하겠습니다!
- close #169
> Feat: 레시피 리팩토링 및 멤버 검증 기능 구현

- src/main/java/com/example/dgbackend/domain/member/dto/MemberRequest.java
- src/main/java/com/example/dgbackend/global/jwt/controller/JwtController.java
- src/main/java/com/example/dgbackend/global/jwt/dto/AuthRequest.java
- src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
- src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java
- Provider와 ProviderId만 보내었을 때 가입된 유저인지 새로 가입한 유저인지 반환하는 API
- API 내용
- 가입되지 않은 유저일 때
- 가입한 유저일 때
-
- #218
> Feat: 새 유저/기존 유저 구분 API

- src/main/java/com/example/dgbackend/domain/term/Term.java
- src/main/java/com/example/dgbackend/domain/term/TermType.java
- src/main/java/com/example/dgbackend/domain/term/repository/TermRepository.java
- src/main/java/com/example/dgbackend/domain/termagree/TermAgree.java
- src/main/java/com/example/dgbackend/domain/termagree/controller/TermAgreeController.java
- src/main/java/com/example/dgbackend/domain/termagree/dto/TermRequestDTO.java
- src/main/java/com/example/dgbackend/domain/termagree/dto/TermResponseDTO.java
- src/main/java/com/example/dgbackend/domain/termagree/repository/TermAgreeRepository.java
- src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandService.java
- src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeQueryService.java
- src/main/java/com/example/dgbackend/domain/termagree/service/TermAgreeQueryServiceImpl.java
- 약관 관련한 기능 구현했습니다.
- Term 엔티티 수정했습니다. 
title -> termType 이넘으로 수정함 (PRIVACY, CONTENT, AGE, COPYRIGHT, SERVICE_CHANGE, MARKETING)
- TermAgree 엔티티 수정했습니다.
approve 삭제. 해당 테이블에는 약정을 수락한 내용만 저장합니다.
API 구현
- 약관 수락
- 약관 삭제
- 멤버의 약관 조회
약관 수락
약관 삭제
약관 목록 조회
-
- #220
> 220 [FEAT] 약관 기능 구현

- src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- 기존 검색 API를 해시태그 및 내용을 통해 검색할 수 있도록 기능을 추가합니다.
- 오늘의 조합, 주간 베스트 조합 검색 API 해시태그 검색 기능 추가
- 오늘의 조합, 주간 베스트 조합 검색 API 내용 검색 기능 추가
- 레시피북 검색 API 해시태그 검색 기능 추가
- 해당 기능 모두 쿼리문 수정을 통해 구현하였습니다.
- `LEFT JOIN`과 `IN` 방식 중 테스트해보았지만 현재는 쿼리문 차이가 없어, `IN` 절의 서브 쿼리가 더 적으므로 IN 구문을 사용하여 추후 더 많은 데이터 조회시에도 효율적으로 조회할 수 있도록 `IN` 절을 사용하였습니다.
`요아정` 이라는 해시태그를 검색 했을 때, 해당 해시태그가 존재하는 게시글이 검색되는 모습을 확인할 수 있습니다.
- Combination은 제목 + 내용 + 해시태그로 검색합니다.
- 레시피북은 PM과 상의하여 제목 + 해시태그로만 검색하도록 하였습니다.
- 클라이언트측에서 글을 작성할 때, 해시태그에 #이 붙어서 저장될 때가 있고 아닐 때가 있는 것 같아 추후 확인하여 프론트측에서 수정이 이루어진다면 데이터베이스가 깔끔하게 보일 것 같습니다!
- close #227
> Feat: 해시태그를 통한 검색 기능 추가

- src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
- 오늘의 조합 상세정보 조회 시, recommnendId가 null 값이 아닌 경우 반환
@JsonInclude(Include.NON_NULL) 어노테이션을 통해 구현
- recommendId가 있을 경우
- recommendId가 없을 경우
-  
- #237
> Refactor: 오늘의 조합 상세조회 Response 수정

- src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
- src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
- src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
- src/main/java/com/example/dgbackend/domain/recipeimage/RecipeImage.java
- src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
- src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageResponse.java
- src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java
- src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
- Recipe Image 업로드 방식을 Combination Image와 동일하게 수정 하였습니다.
- 기존 Combination Image 업로드 방식과 동일하게 수정 및 기존 로직 삭제
- 관련하여 DTO 수정 및 Entity에 메소드를 추가하였습니다.
- 이와 관련하여 기존 api는 삭제하였습니다.
위와 같이 작성 후, 이미지 수정 진행
두번째 파일만 삭제 후 조회 확인
DB에서도 삭제 확인
- 기존 Combination Image 업로드 방식과 똑같이 구현했지만, 삭제가 처리되지 않고 남아있는 문제가 발생하여 오래걸렸습니다.
```
@Modifying
@Query("DELETE from RecipeImage ri where ri.imageUrl = :imageUrl")
void deleteByImageUrl(String imageUrl);
```
위와 같이 JPQL을 통해 구현하니 잘 작동하였습니다. 기존 Combination Image와 동일하게 작성했는데, 해당 문제가 왜 발생했는 지 아직 잘 모르겠습니다 ㅠㅠ 더 알아보는 중인데, 일단 모이치가 수정해야해서 Merge하려고 합니다!
관련 이슈 아시는 분 있으면 코멘트 부탁드립니다!
- close #239
> [CHANGE] 레시피 이미지 업로드 방식 수정

- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/CachedRecommendImage.java
- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/repository/CachedRecommendImageRepository.java
- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageCommandService.java
- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageCommandServiceImpl.java
- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageQueryService.java
- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageQueryServiceImpl.java
- src/main/java/com/example/dgbackend/domain/cachedRecommendImage/service/CachedRecommendImageScheduler.java
- src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
- src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
- CachedRecommendImage 캐싱테이블 추가
- 추천 로직에서 캐싱테이블 조회 로직 추가
- 캐시 TTL관리를 위한 스케줄러 구현 (매일 0시 0분 1초 실행)
캐싱 전 소요시간 약 19초
캐시 hit 소요시간 약 3초
-
- #170
> [FEAT] 추천 이미지 캐싱 구현

- src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
- 회원정보 수정 시에 닉네임 중복 검사하는 로직 추가
- 수정 성공시 
- 중복되는 닉네임이 있을 떄 
-
- #257
> [Fix] 닉네임 중복 검사 로직 추가

- src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
- 멤버의 추천 기본 정보 GET API를 구현합니다.
- recommend-info url로 GET api를 구현했습니다.
-
- #262
> [FEAT] 추천 정보 get API 구현

- src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
- src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
- 멤버 정보 수정 시 본인 닉네임 중복 검사 제외
- 리프레시 토큰 만료기한 추가
- 기존 닉네임으로 수정 요청하여도 중복에 걸리지 않음
- 토큰 해독시 만료 기한 확인 가능
-
- #264
> [FIX] 닉네임 중복 검사 로직 변경 & 만료시간 추가

- .gitignore
- build.gradle
- src/main/java/com/example/dgbackend/domain/memberblock/controller/MemberBlockController.java
- src/main/java/com/example/dgbackend/domain/recommend/controller/RecommendController.java
- src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java
- src/main/java/com/example/dgbackend/global/config/log/Interceptor.java
- src/main/java/com/example/dgbackend/global/config/log/LogAspect.java
- src/main/java/com/example/dgbackend/global/config/log/LogExecutionTime.java
- src/main/java/com/example/dgbackend/global/config/log/LogWebConfig.java
- src/main/java/com/example/dgbackend/global/exception/ApiException.java
- src/main/resources/log4j2.xml
- Log4j2를 이용하여 일반 로그와 에러 로그를 파일로 만드는 기능을 구현했습니다.
- 로그 파일의 위치는 root/logs 로 설정하였습니다. 일반 로그와 에러 로그는 각각 다른 파일로 관리되며, 오늘이 아닌 로그 파일의 경우 아래와 같이 날짜가 표시됩니다.
- 콘솔 로그가 다음과 같이 수정되었습니다.
- Spring Boot의 기본 로그가 Logback으로 설정되어 있어서 그걸 비활성화 해주고 Log4j2를 추가해주었습니다.
- [Feat: Log4j2 의존성 추가](https://github.com/UMC5th-DrinkingGourmet/dg-BackEnd/commit/2cc5834a6561e88ea17d3e00580be323576d62a7)
- Request가 들어오는 Flow는 Filter -> DispatcherServlet -> HandlerInterceptor -> controller 순입니다. 먼저 Interceptor을 이용해서 API 호출 시 preHandle에서 Request URI가, postHandle에서 Response Status가 찍히도록 하였습니다.
- [Feat: Interceptor preHandle, postHandle, afterCompletion 구현](https://github.com/UMC5th-DrinkingGourmet/dg-BackEnd/commit/fb6cad627f71eab34039386f1963595f76c30140)
- 다음 예시와 같이 출력됩니다.
- <img width="1326" alt="image" …
> Feat: 로그 기능 구현

- src/main/java/com/example/dgbackend/domain/member/controller/MemberRestController.java
- src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
- src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
- src/main/java/com/example/dgbackend/global/s3/S3Service.java
- profileImage에 null 값이 들어갈 수 있게 수정
- 기존 null로 설정된 이미지였으면 삭제 시 오류 발생 -> 해당 이미지가 있을 경우에만 삭제하도록 변경
- MemberController에서 해당 MultipartFile의 required 조건을 false로 명시 -> file이 null로 와도 오류 X
-
- #269
> Fix: 프로필 사진 수정 로직 수정

- src/main/java/com/example/dgbackend/domain/combination/Combination.java
- src/main/java/com/example/dgbackend/domain/combination/service/CombinationScheduler.java
- src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
- src/main/java/com/example/dgbackend/domain/recipe/service/RecipeScheduler.java
- 메인에서 불러올 때 셋 중 하나라도 삭제된 항목이 있으면, 랜덤 로직을 다시 불러옴
- RecipeSchedular, CombinationSchedular 둘 다 동일하게 변경
- 메인에서 조회 호출이 있을 경우, 미리 저장된 항목 중 하나라도 삭제가 되어있으면 random top 3를 다시 뽑아서 저장 후 반환
- 자정에 똑같이 한 번씩 돌아감 
-
-
> Fix: 메인 조회 로직 임시조치
