UMC5th-DrinkingGourmet/dg-BackEnd

src/main/java/com/example/dgbackend/global/common/response/ApiResponse.java
src/main/java/com/example/dgbackend/global/common/response/code/BaseCode.java
src/main/java/com/example/dgbackend/global/common/response/code/BaseErrorCode.java
src/main/java/com/example/dgbackend/global/common/response/code/ErrorReasonDto.java
src/main/java/com/example/dgbackend/global/common/response/code/ReasonDto.java
src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
src/main/java/com/example/dgbackend/global/common/response/code/status/SuccessStatus.java

Related: #5
- 공통 응답 생성
- api 응답시 Json 구조를 통일시켰습니다.
- 스프링 8주차 워크북을 참고했습니다.
- 자세한 동작 원리는 워크북을 참고하면 좋을 것 같습니다.
- close #5

Feat: 공통 응답 설정

---

src/main/java/com/example/dgbackend/domain/recommend/Recommend.java

Related: #1
- Recommend Entity를 수정합니다.
- 주류 추천 페이지에서 최초 1회 정보 입력 시 취할 정도 입력을 위해 String -> Integer로 변환하였습니다.
- 엔티티 매핑을 PR로 확인 받고 진행하고자 했는데 develop에 바로 push 해버렸습니다.. 다음 번 부턴 주의하도록 하겠습니다!
- 각자 clone 받아온 뒤 Entity 확인해주시면 감사하겠습니다! 단방향 매핑만 진행하였습니다.
- close #1

Docs: Recommend Entity 수정

---

src/main/java/com/example/dgbackend/global/common/response/ApiResponse.java
src/main/java/com/example/dgbackend/global/exception/ApiException.java
src/main/java/com/example/dgbackend/global/exception/ExceptionAdvice.java

Related: #8
- 에러 핸들러 설정 완료
- API 통신 시 발생하는 예외 처리 코드를 작성하였습니다.
- UMC Server 8주차 에러 핸들러 부분을 참고하였습니다.
- 모든 도메인의 Handler를 만들면 중복된 부분이 많을 거 같아 ApiException로 예외 처리 하도록 구현하였습니다.
- close #8

Feat : 에러 핸들러 설정 완료

---

src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
src/main/java/com/example/dgbackend/domain/combination/domain/Combination.java
src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
src/main/java/com/example/dgbackend/domain/combinationimage/CombinationImage.java
src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java

- 오늘의 조합 API 중 홈 페이지 조회 API 구현
- Combination과 CombinationImage의 데이터를 페이징하여 DTO로 전송합니다. 
-
- close #21

feat: 오늘의 조합 홈 조회 API 구현

---

src/main/java/com/example/dgbackend/global/s3/S3Service.java

Related: #46
- S3에 저장되어 있는 파일명.확장자로 전달되지 않아, S3 객체(이미지)가 삭제 되지 않아 수정하였습니다.
- S3Service 이미지 삭제 메서드 수정하여 오늘의 조합 삭제 API 수정하기
1. S3에 생성된 이미지
<br/>
2. 생성된 이미지 주소를 CombinationImage 테이블에 더미데이터 생성하기
<br/>
3. 연관된 Combination, CombinationImage를 삭제하여 데이터베이스와 S3에서 이미지 데이터 삭제하기
- close #46

FIX: 오늘의 조합 삭제 API 수정

---

src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java

Fix: ErrorStatus 수정

---

src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java

- 오류 수정하여 Main에 merge 합니다
-
-
-

[Main Merge] 3회차

---

src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
src/main/java/com/example/dgbackend/domain/member/Member.java

Related: #64
- Merge 시 놓친 conflict 해결
- CombinationCommentQueryServiceImpl 코드 수정
-
- close #64

fix: Merge Conflict 해결

---

src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentRequest.java
src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java
src/main/java/com/example/dgbackend/domain/recipelike/dto/RecipeLikeResponse.java

- 레시피 Swagger 설정
- 
- DTO는 @Schema(description = "", example = "") 형식으로 통일하였습니다.
- Controller는 
- @Operation(summary = "", description = "")
- @Parameter(name = "", description = "", required = true, example = "1", in = ParameterIn.QUERY)
형식으로 통일하였습니다.
- 코드다 너무 지저분해지는 것 같아 ApiResponse 적용은 하지 않았는데 필요하다면 추후 추가하겠습니다!!
- Close  #69

Docs : 레시피 Swagger 설정

---

src/main/java/com/example/dgbackend/global/config/SwaggerConfig.java

- swagger Failed to fetch 오류 해결
- 아래와 같은 오류를 해결합니다.
-
- close #85

Fix: swagger Failed to fetch 오류 해결

---

src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentCommandService.java

Fix: updateComment 반환 타입 수정

---

src/main/java/com/example/dgbackend/domain/combination/Combination.java
src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/member/service/MemberQueryService.java
src/main/java/com/example/dgbackend/domain/member/service/MemberQueryServiceImpl.java
src/main/java/com/example/dgbackend/global/jwt/dto/AuthResponse.java
src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java

- 댓글 조회 API 수정 및 CommentResult 수정
1. (삭제 전) 댓글 조회 결과
2. (삭제 후) 댓글 조회 결과
-
- close #118

fix: 댓글 조회 API 수정 및 CommentResult 수정

---

src/main/java/com/example/dgbackend/AppInitialization.java
src/main/java/com/example/dgbackend/DgBackEndApplication.java
src/main/java/com/example/dgbackend/domain/combination/controller/CombinationController.java
src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java
src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryService.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationScheduler.java
src/main/java/com/example/dgbackend/domain/combinationimage/repository/CombinationImageRepository.java
src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeScheduler.java
src/main/java/com/example/dgbackend/domain/recipeimage/repository/RecipeImageRepository.java

- 메인 최상단 주간 베스트 조회 API 구현
- 메인 로테이션 오늘의 조합 조회 API 구현
- 메인 로테이션 레시피북 조회 API 구현
1. 메인 최상단 주간 베스트 조회 API
- API 내용
- 성공 화면 
2. 메인 로테이션 오늘의 조합 조회 API 구현
- API 내용
- 성공 화면 (갱신 전)
- 성공 화면 (갱신 후)
3. 메인 로테이션 레시피북 조회 API 구현
- API 내용
- 성공 화면(갱신 전)
- 성공 화면(갱신 후
-
- #107

FEAT : 메인 최상단 주간 베스트 조회 API & 메인 로테이션 오늘의 조합 조회 API & 메인 로테이션 레시피북 조회  API

---

src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryService.java
src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java

Related: #114
- 오늘의 조합 좋아요 API에 멤버 어노테이션을 적용하였습니다.
-
-
- close #114

Fix: 오늘의 조합 좋아요 API 멤버 어노테이션 적용

---

src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
src/main/java/com/example/dgbackend/domain/recipeimage/dto/RecipeImageResponse.java
src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java

- 레시피북 조회 시 이미지 URL 추가 & 닉네임 변경 & 페이징
- 레시피북 리스트 조회 시 각 레시피 북 이미지 URL 추가
- 레시피북 리스트 조회 시 각 페이징 추가
- 닉네임 변경
- memberName 대신 닉네임 반영
이미지 URL 추가 & 닉네임 변경 & 페이징
---
- Close  #113

[FEAT] 레시피북 Response 변경

---

src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java

- memberName -> memberNickname 으로 변경
- 프론트파트 요청으로 Recipe 반환 변수 중 memberName을 memberNickname 으로 변경
-
-

fix : memberName -> memberNickname 으로 변경

---

src/main/java/com/example/dgbackend/domain/recipe/Recipe.java

- Reciepe Entity에서 List에 Default 값 추가
- Recipe Entity에 recipeImageList 추가 이후 Recipe Post 시  recipeImageList를 dto로 변환하는 과정에서 Null 문제가 발생하였습니다.
Null 처리를 따로 해줘도 되지만 코드가 중복될 것 같아 Builder.Default로 생성시 빈 배열이 들어가도록 설정하였습니다.
-
-

Refactor : List Default값 추가

---

src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
src/main/java/com/example/dgbackend/domain/recipelike/controller/RecipeLikeController.java

- MemberObject 추가
- Recipe 도메인에 MemberObject가 누락되어 추가하였습니다.
-
Close #127

fix : MemberObject 추가

---

src/main/java/com/example/dgbackend/domain/recommend/dto/RecommendResponse.java
src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java
src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryService.java
src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java

ResponseDTO에 recommendID추가
- RecommendResponseDTO에 ResponseID추가
- Recommend관련 API Response에 RecommendID가 누락되어있었습니다. ResponseDTO에 ID를 추가하였습니다.
-
- close #130

Fix: 주류 추천 ResponseDTO 변경

---

src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java

- 오늘의 조합 상세보기, 댓글 작성 DTO 수정
- 오늘의 조합 상세보기 DTO 수정 - name -> nickname
- 오늘의 조합 댓글 작성 DTO 수정 - updatedAt -> createdAt
-
- close #134

FIX: 오늘의 조합 홈 페이지, 상세보기, 댓글 작성 DTO 수정

---

src/main/java/com/example/dgbackend/domain/recipe/Recipe.java
src/main/java/com/example/dgbackend/domain/recipe/controller/RecipeController.java
src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeRequest.java
src/main/java/com/example/dgbackend/domain/recipe/dto/RecipeResponse.java
src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeService.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java

- 레시피북 프론트 요청사항에 맞게 수정합니다
레시피북 post body 수정
- 레시피북 댓글에 댓글 작성 시간, 댓글작성한 사람 닉네임, 프로필이미지, 답글갯수
-  레시피북 검색 + 댓글 조회에서 페이징 변수 추가
- 레시피북 홈조회 + 상세조회에서 좋아요 정보 추가
-
-

Refactor : 레시피북 프론트 요청

---

.github/workflows/docker-deploy.yml

- Docker 컨테이너 시간 설정을 서울로 하여 시간 설정 테스트
-
-
-

Fix: Docker 컨테이너 시간 설정

---

src/main/java/com/example/dgbackend/domain/recommend/service/RecommendCommandServiceImpl.java

- 이미지 생성 모델 변경 및 프롬프트 수정
- Dall-e-2 -> Dall-e-3변경 (application.yml파일 수정해야함)
- 이미지 생성 프롬프트 수정
https://www.notion.so/cf32abb1c4ee417080d8a19ee6edc372?pvs=4
노션에서 프롬프트 내용 및 이미지 생성 결과를 볼 수 있습니다.
-
- close #62

Fix: 이미지 생성 프롬프트 수정

---

src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java

Fix: 오늘의 조합/레시피 홈 조회시 생성일 순으로 내림차순

---

src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
src/main/java/com/example/dgbackend/domain/recipe/service/RecipeServiceImpl.java
src/main/java/com/example/dgbackend/domain/recommend/repository/RecommendRepository.java
src/main/java/com/example/dgbackend/domain/recommend/service/RecommendQueryServiceImpl.java

Fix: 주류 추천 및 내가 작성한 글 조회시 생성일 순으로 내림차순

---

build.gradle
src/main/java/com/example/dgbackend/domain/combination/repository/CombinationRepository.java
src/main/java/com/example/dgbackend/domain/combinationcomment/CombinationComment.java
src/main/java/com/example/dgbackend/domain/combinationcomment/dto/CombinationCommentResponse.java
src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/enums/ReportReason.java
src/main/java/com/example/dgbackend/domain/enums/ReportTarget.java
src/main/java/com/example/dgbackend/domain/enums/State.java
src/main/java/com/example/dgbackend/domain/recipe/repository/RecipeRepository.java
src/main/java/com/example/dgbackend/domain/recipecomment/RecipeComment.java
src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentRequest.java
src/main/java/com/example/dgbackend/domain/recipecomment/dto/RecipeCommentResponse.java
src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
src/main/java/com/example/dgbackend/domain/report/Report.java
src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java
src/main/java/com/example/dgbackend/domain/report/dto/ReportRequest.java
src/main/java/com/example/dgbackend/domain/report/repository/ReportRepository.java
src/main/java/com/example/dgbackend/domain/report/service/ReportService.java
src/main/java/com/example/dgbackend/domain/report/service/ReportServiceImpl.java
src/main/java/com/example/dgbackend/domain/reportimage/ReportImage.java
src/main/java/com/example/dgbackend/domain/reportimage/ReportImageController.java
src/main/java/com/example/dgbackend/domain/reportimage/ReportImageRepository.java
src/main/java/com/example/dgbackend/domain/reportimage/ReportImageService.java
src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java

- 신고하기 API 구현
```
implementation 'org.springframework.boot:spring-boot-starter-mail'
```
- 메일 관련 의존성 추가
신고한 사람, 신고 대상(글, 댓글 등),신고 대상의 내용, 신고 사유, 신고 대상의 타입을 필드로 가짐
- 신고 이유 ENUM 저장
```java
ABUSIVE_LANGUAGE("욕설, 비속어, 혐오 발언 등 타인에게 불쾌감을 주는 내용" , "1일 정지"),
DEFAMATION("타인을 모욕하거나 명예를 훼손하는 내용", "7일 정지"),
PORNOGRAPHY_ILLEGAL_CONTENT("음란물, 불법적인 내용" , "30일 정지"),
UNAUTHORIZED_PERSONAL_INFO("타인의 개인정보를 무단으로 수집하거나 공개", "영구 정지"),
COPYRIGHT_INFRINGEMENT("타인의 저작권을 침해", "영구 정지"),
TERMS_VIOLATION("기타 커뮤니티 이용약관에 위반되는 행위" , "임시 정지");
```
- 신고 타입을 ENUM 저장
```java
COMBINATION("조합글"),
RECIPE("레시피글"),
COMBINATION_COMMENT("조합 댓글"),
RECIPE_COMMENT("레시피 댓글");
```
- 신고하기 uri : `/member/reports`
- report() : 이전 신고가 존재하는 지 검증하고, 레포트를 생성해 저장 후 분류합니다.
- duplicateReport() - 이전에 중복되는 신고가 존재하는 지 검증합니다.
- sortReport() - 각각의 신고 …

Feat : 신고하기 API

---

build.gradle
src/main/java/com/example/dgbackend/domain/member/Member.java
src/main/java/com/example/dgbackend/domain/member/service/MemberCommandService.java
src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
src/main/java/com/example/dgbackend/domain/report/service/ReportServiceImpl.java
src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java
src/main/java/com/example/dgbackend/global/config/SecurityConfig.java
src/main/java/com/example/dgbackend/global/exception/ExceptionAdvice.java
src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
src/main/java/com/example/dgbackend/global/jwt/filter/CustomAuthenticationEntryPoint.java
src/main/java/com/example/dgbackend/global/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java

- 신고하기 API 추가 구현
1. 영구정지 시 DB 롤 Reported로 변경
멤버 신고 API
신고 후 DB 롤
2. 임시정지 시 해당 기간 동안 Redis에 해당 멤버 추가
당하기 전 Redis
임시정지 신고 API
임시정지 신고 당한 후 Redis
해당 멤버 키 만료 시간 확인
3. 신고 시 신고 당한 멤버 로그인에서 검증 구현
1번에서 신고당한 멤버로 로그인 시 
4. 신고 시 신고 당한 멤버 강제 로그아웃
신고 당할 멤버 로그인
Redis에서 신고당한 멤버 리프레시 토큰 삭제
이후 해당 멤버로 다른 API 조회
- 프론트 쪽에서 신고 당한 멤버 강제로 로그아웃 되는 지 테스트 필요
- #182

Feat: 신고하기 API 추가 구현

---

src/main/java/com/example/dgbackend/domain/combination/service/CombinationQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/combinationcomment/controller/CombinationCommentController.java
src/main/java/com/example/dgbackend/domain/combinationcomment/repository/CombinationCommentRepository.java
src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryService.java
src/main/java/com/example/dgbackend/domain/combinationcomment/service/CombinationCommentQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/memberblock/service/MemberBlockServiceImpl.java
src/main/java/com/example/dgbackend/domain/recipecomment/controller/RecipeCommentController.java
src/main/java/com/example/dgbackend/domain/recipecomment/repository/RecipeCommentRepository.java
src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentService.java
src/main/java/com/example/dgbackend/domain/recipecomment/service/RecipeCommentServiceImpl.java
src/main/java/com/example/dgbackend/global/common/response/code/status/ErrorStatus.java

- 차단한 멤버의 댓글이 타 게시글에서 보이지 않도록 수정
- 본인은 차단할 수 없도록 처리
- 이전과 동일한 방식으로 구현하였습니다.
- 코딩 컨벤션을 적용하느라 충돌이 많이 날 것 같습니다..!! 제가 해결하겠습니다!
- close #190

Fix: 댓글 차단 구현, 본인 차단 에러 수정

---

src/main/java/com/example/dgbackend/domain/combinationlike/service/CombinationLikeQueryServiceImpl.java
src/main/java/com/example/dgbackend/domain/member/dto/MemberResponse.java
src/main/java/com/example/dgbackend/domain/member/service/MemberCommandServiceImpl.java
src/main/java/com/example/dgbackend/domain/member/service/MemberService.java
src/main/java/com/example/dgbackend/global/jwt/service/AuthService.java

- 리프레시토큰이 만료되었는데도 재발급이 요청되는 오류 해결
- 위와 동일
- if문 속 조건문 변경
-
- #203

Fix : 액세스토큰 재발급 오류 해결

---

src/main/java/com/example/dgbackend/domain/term/TermType.java

- 약관 정책 변경에 따라 enum을 수정했습니다.
- TermType이넘 수정
- DB 스키마 변경
-
- #238

[CHANGE] 약관 정책 수정

---

src/main/java/com/example/dgbackend/domain/combination/dto/CombinationRequest.java
src/main/java/com/example/dgbackend/domain/combination/service/CombinationCommandServiceImpl.java

- Combination 추가시 Recommend 참조가 안되던 오류를 수정했습니다.
- Combination 생성 코드에서 Recommend 추가 부분이 누락되어있어 추가하였습니다.
마지막 Id 8번이 제대로 등록된 모습입니다.
-

[fix] Combination 추가 오류 수정

---

src/main/java/com/example/dgbackend/domain/combinationlike/controller/CombinationLikeController.java
src/main/java/com/example/dgbackend/domain/recipeimage/controller/RecipeImageController.java
src/main/java/com/example/dgbackend/domain/recipeimage/service/RecipeImageService.java
src/main/java/com/example/dgbackend/domain/report/controller/ReportController.java

- API에 스웨거 설명을 추가합니다.
- 신고하기 설명 추가
- 오늘의 조합 좋아요 설명 추가
- 레시피북 이미지 조회 및 삭제 API 제거
-
- close #249

Docs: 스웨거 설명 추가, Chore: 레시피북 이미지 조회 및 삭제 API 제거

---

src/main/java/com/example/dgbackend/domain/combination/dto/CombinationResponse.java

- CombinationResult에 recommend 필드를 추가하였습니다.
-
-
- close #252

Feat: CombinationResult에 recommend 필드 추가

---

src/main/java/com/example/dgbackend/global/jwt/JwtProvider.java
src/main/java/com/example/dgbackend/global/jwt/filter/JwtAuthenticationFilter.java

- access token 예외처리 수정
- 유효하지 않은 access token과 만료 기한이 지난 token 구별
-
-

 Fix: access token 예외처리 수정

---

src/main/java/com/example/dgbackend/domain/report/service/ReportServiceImpl.java

[Docs] import 문 정리
